name: polyweb.digital CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Build & Push PolyWeb Image"
        run: |
          docker build . --tag polyweb/polyweb.digital:latest
          docker push polyweb/polyweb.digital:latest

      - name: Deploying Image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.PASSWORD }} | sudo -S docker stop polyweb.digital
            echo ${{ secrets.PASSWORD }} | sudo -S docker container rm polyweb.digital
            echo ${{ secrets.PASSWORD }} | sudo -S docker pull polyweb/polyweb.digital
            echo ${{ secrets.PASSWORD }} | sudo -S docker run -p 80:80 --name polyweb.digital -d polyweb/polyweb.digital
